### ISSUE TITLE
xlsx file not open

### ISSUE THREAD

**Issue by twixi** [Plagiatus/MCStatsToExcel#1]
xlsx file not open

**Comment by Plagiatus** [comment]
Please, be more specific. A lot more specific.

Is there an error while running the program? Does it not create the file? Does it create the file but you're unable to open it? What program are you using? Can you provide an example of a broken file? What is your workflow? Etc.

Please, rather give me too much info than too little.

**Comment by twixi** [comment]
![image](https://github.com/Plagiatus/MCStatsToExcel/assets/7196070/ca390c72-105c-45d9-9bd1-0368e4dab97d)
software make .xlsx file but i`m unable to open it! (uuid not found because it is not an official server)
[MCStatsToExcel-win.exe](https://github.com/Plagiatus/MCStatsToExcel/releases/download/0.0.1/MCStatsToExcel-win.exe)
![image](https://github.com/Plagiatus/MCStatsToExcel/assets/7196070/5d0d6aae-d5bf-4bdb-b4e5-77126c6818ac)
broken [file](https://dimboy.com/MCStatsToExcel.xlsx)

**Comment by Plagiatus** [comment]
Okay, the file you attached seems to be basically empty. Can you provide the input values you've got?

**Comment by Plagiatus** [comment]
I've released a new version of the program. Not directly tied to your issue, but you should update to 0.0.2 nonetheless.

If you still have trouble, please provide the input stat files you're using so I can try to debug the issue.

**Comment by twixi** [comment]
xlsx file not open in 0.0.2 too

**Comment by Plagiatus** [comment]
Can you please provide the input files (the stat files in particular, as you're not using a config file)?

Also, can you provide a step-by-step instruction on what _exactly_ you're doing? For example:

1. I copy the .exe file into the stats folder
2. I open a cmd terminal in the folder
3. I run the exe file through the terminal with this command: "...."
4. I get this output: [image here] (in case it's any different from what you posted above, _especially_ if you're getting errors)
5. I try to open the resulting xlsx file but I get this error message when opening it [image here]

**Comment by twixi** [comment]
my json stats 1.7.10 [https://pastebin.com/T4HeZNhm](https://pastebin.com/T4HeZNhm)

**Comment by twixi** [comment]
is no longer relevant, I wrote a script on Python

**Comment by Plagiatus** [comment]
oh my god, you're using minecraft 1.7? wow, that would've been very helpful information.

Just as much as the stats file is helpful, I can immediately see the issue.
But since it's no longer relevant to you, I guess I can take my time to fix this then. :D

**Comment by twixi** [comment]
> oh my god

welcome [ahah](https://mc.emelgame.com)
